import turtle
print(" The Turtle has imported")
turtle.getscreen()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.shape("turtle")
turtle.circle(100)
turtle.exitonclick()
print(" The square is ready ")
